sb-web:
    image: jacobbermudes/sb-server:latest
    container_name: sb-web
    restart: always
    networks:
      - surfboost
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sb-web.entrypoints=websecure"
      - "traefik.http.routers.sb-web.rule=Host(`surfboost.ru`) || Host(`www.surfboost.ru`)"
      - "traefik.http.routers.sb-web.tls=true"
      - "traefik.http.routers.sb-web.tls.certresolver=myresolver"
      - "traefik.http.services.sb-web.loadbalancer.server.port=8082"
